%%[
VAR @COUNTRY, @HEADER, @SUBJ, @EMAILNAME, @NUMBER
SET @EMAIL = emailaddr
SET @DE1 = LookupRows('TB00_Brabbu_Leads', 'Email', @EMAIL)
IF ROWCOUNT (@DE1) > 0 THEN
  SET @ROW = ROW(@DE1, 1)
  SET @LEADCITY = FIELD(@ROW, 'City')
  SET @LEADCOUNTRY = FIELD(@ROW, 'Country')
  SET @LEADCCODE = FIELD(@ROW, 'CountryCode')
  SET @FONTE = 'LEAD'
ELSE
  SET @ROW = ROW(@DE3, 1)
  SET @LEADCITY = FIELD(@ROW, 'MailingCity')
  SET @LEADCOUNTRY = FIELD(@ROW, 'MailingCountry')
  SET @LEADCCODE = FIELD(@ROW, 'MailingCountryCode')
  SET @FONTE = 'CONTACTO'
ENDIF

IF NOT EMPTY (@LEADCITY) THEN
 SET @DE2 = LOOKUPROWS('TB01_CBC_CONTEUDOS_BB', 'CITY', @LEADCITY)
 IF ROWCOUNT (@DE2) > 0 THEN
  SET @ROW2 = ROW(@DE2, 1)
  SET @CITY = FIELD(@ROW2, 'CITY')
  SET @COUNTRY = FIELD(@ROW2, 'COUNTRY')
  SET @CCODE = FIELD(@ROW2, 'COUNTRYCODE')
  SET @SUBJ = FIELD(@ROW2, 'SUBJ1')
  SET @HEADER = FIELD(@ROW2, 'HEADER1')
  SET @EMAILNAME = FIELD(@ROW2, 'EMAILNAME1')
  SET @ID_EMAIL = FIELD(@ROW2, 'ID_EMAIL1')
  SET @UTMSOURCE = FIELD(@ROW2, 'utm_source1')
  SET @UTMMEDIUM = FIELD(@ROW2, 'utm_medium1')
  SET @UTMCAMPAIGN = FIELD(@ROW2, 'utm_campaign1')
 ENDIF
ELSEIF EMPTY (@LEADCITY) AND NOT EMPTY (@LEADCCODE) THEN
 SET @DE2 = LOOKUPROWS('TB01_CBC_CONTEUDOS_BB', 'COUNTRYCODE', @LEADCCODE)
 IF ROWCOUNT (@DE2) > 0 THEN
  SET @ROW2 = ROW(@DE2, 1)
  SET @CITY = FIELD(@ROW2, 'CITY')
  SET @COUNTRY = FIELD(@ROW2, 'COUNTRY')
  SET @CCODE = FIELD(@ROW2, 'COUNTRYCODE')
  SET @SUBJ = FIELD(@ROW2, 'SUBJ1')
  SET @HEADER = FIELD(@ROW2, 'HEADER1')
  SET @EMAILNAME = FIELD(@ROW2, 'EMAILNAME1')
  SET @ID_EMAIL = FIELD(@ROW2, 'ID_EMAIL1')
  SET @UTMSOURCE = FIELD(@ROW2, 'utm_source1')
  SET @UTMMEDIUM = FIELD(@ROW2, 'utm_medium1')
  SET @UTMCAMPAIGN = FIELD(@ROW2, 'utm_campaign1')
 ENDIF
ENDIF
]%%

%%=ContentBlockByID(@ID_EMAIL)=%%
